spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medreminder?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: dirtig-xyxzem-0piwkA
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
